baseURL: https://Parthdsi.github.io/
languageCode: en-us
title: Jack of All Trades
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
 # main:
   # - identifier: blog
    #  name: Blog
     # title: Blog posts
      #url: /blogs
      #weight: 1
    
   # - identifier: gallery
    #  name: Gallery
     # title: Blog posts
      #url: /gallery
      #weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Jack of All Trades"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Parth."
    subtitle: "...but I like to call myself a Jack of all Trades"
    content: "The content of this website will take you through my experience, and hopefully help you learn a little more about me."
    image: /me.png
    button:
      enable: true
      name: "Resume"
      url: https://drive.google.com/file/d/1L4ssDJlH1FIMUOTh92PKFjWDuaxD_ei_/view?usp=sharing
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Parthdsi
        - icon: fab fa-twitter
          url: https://twitter.com/parthdsi


  # About
  about:
    enable: true
    title: "About Me"
    image: /me3.png
    content: |-
      Hey! I’m Parth, a Jack of all Trades. My passion for not having one set passion is what has defined most of my life today. Growing up I loved sports and weight lifting, but at the same time I felt as strong an affection for both music and the fine arts. Two starkly different things. To top it all off, I was someone who loved learning about history and my ability to suck in information led me to excel at academics as well. The common trend here seems to be that I like a lot of different things. 
      
      In fact, this trend is what led me to pursue Management Engineering at the University of Waterloo. As a Management Engineer, I am truly able to live up to the term: a Jack of all Trades. This is because as Management Engineers we are taught and able to excel in vast engineering disciplines. Whether that include circuitry and hardware, process optimization, computer programming, or even economics. 
      
      Unfortunately, I’ve only allowed myself this much space to write about me, so feel free to get in contact with me so we can chat! 
    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    items:
      - job: "Operations Coordinator"
        company: "Bombardier"
        companyUrl: "http://www.bombardier.com/"
        date: "May 2022 - August 2022"
        content: |
          - Tracked 200+ data points to identify and rectify bottlenecks in production sequence increasing efficiency by 20%
          - Designed and applied new clocking accuracy process to increase productivity by 1.5x
          - Carried out the creation of a Digital Handover Template by utilizing feedback loops and continuous improvement models
      
      - job: "Project Manager"
        company: "Kickstand"
        companyUrl: "https://mykickstand.ca/"
        date: "January 2021 - September 2021"
        content: |
          - Attained 80% month-over-month growth rate by analyzing social media and developing growth strategy
          - Directed team of 15 and enacted cross-team collaboration to complete project 2 weeks before deadline
          - Completed project $500 under budget by delegating tasks and services effectively
      
      - job: "Solutions Analyst"
        company: "VEX Robotics"
        date: "September 2018 - June 2021"
        content: |
          - Developed and prototyped an ideal robot through 10 phases of iterative testing and problem-solving
          - Implemented engineering design process to create status reports and highlight engineering procedure
          - Investigated competitors to analyze cumulative strengths and developed an effective plan that led to ranking 1st out of 16 teams

      - job: "Project Coordinator"
        company: "MACOY"
        date: "September 2018 - June 2021"
        content: |
          - Directed 20 MACOY members to plan a university student speaker series; involved in logistics, outreach, and social media management leading to a successful event with over 150 attendees
          - Collaborated with 4 external partners to execute a community wide program to celebrate talented teens
          - Chaired 15 administrative meetings and mentored 20 members to cultivate the growth of the program
      
      - job: "President and Founder"
        company: "JA Dimensions"
        date: "January 2019 - May 2019"
        content: |
          - Managed 8 employees, oversaw prototyping and production of Virtual Reality Headsets, created a business model, delegated tasks, and assisted Vice Presidents in marketing and finances
          - Sold 200 products within 5 months by designing an effective go-to-market strategy
          - Pitched to over 30+ executives and industry leaders to secure $500 in external revenue

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  
  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Applied Sciences in Management Engineering"
        school: 
          name: "University of Waterloo"
          url: "https://uwaterloo.ca"
        date: "2021 - Present"
        GPA: "3.7 out of 4.0"
        content: |-
          Extracurricular Activities
            - Intramural Sports
            - Mentorship for Incoming First-Year Students
      - title: "High School"
        school:
          name: "Westwood Community High School"
          url: "https://westwood.fmpsdschools.ca"
        GPA: "4.0 out of 4.0"
        content: |-
          Extracurricular Activities
            - VEX Robotics Team, Tournament Champions
            - Student Council, Advocate for Student Needs
            - Green Initiative, Voted 2nd Greenest School in Canada
            - Volleyball and Basketball Starter

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Automated Scheduling
        content: Operated in a team of 5 to build a time tracking tool using Excel, VBA, and Macros to automate schedule creation. Utilized engineering design process for research and testing, resulting in an increase of time efficiency by 35%. Developed 5 status reports, tested prototypes, and updated activity logs.
        image: /Scheduling.png
       # featured:
        #  name: Demo
         # link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
       # links:
        #  - icon: fa fa-envelope
         #   url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          #- icon: fab fa-github
           # url: https://github.com/gurusabarish/hugo-profile
          #- icon: fab fa-twitter
           # url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Finance Manager
        content: Created a financial tracker utilizing Excel, VBA, and Pivot Tables to track personal finances and reduce monthly costs. Reduced manual input time by 50% by automating cash inflow/outflow. Evaluated data sets through pivot tables and scatter plots to visualize and summarize key metrics. Analyzed financial conditions through ratio analysis and provided solutions to improve finances.
        image: /PersonalFin.png
       # featured:
        #  name: Demo
         # link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
       # links:
        #  - icon: fab fa-github
         #   url: https://github.com/gurusabarish/converter

      - title: Investment Risk Analyzer
        content: Programmed a risk analysis tool which calculates moving averages for 6000+ public stocks and compares them to average gains to judge investment risk. Built in Python using NumPy and Pandas along with the Yahoo Finance library
        image: /Stock.jpg
        #featured:
         # name: Demo V2
          #link: https://hugo-profile-2.netlify.app
        badges:
           #- "Hugo"
           #- "Bootstrap"
           #- "Javascript"
       # links:
        #  - icon: fab fa-github
         #   url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: parth.desai@uwaterloo.ca
    btnName: Let's Get in Touch!

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/Parthdsi
      linkedin: https://www.linkedin.com/in/parthdsi/
      twitter: https://twitter.com/parthdsi
      instagram: https://instagram.com/parthdsi
      facebook: https://www.facebook.com/parthdsi

